name: arvan_photos
description: "Storage Photos"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  aws_common: ^0.7.15
  aws_signature_v4: ^0.6.0
  cached_network_image: ^3.4.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_background_service: ^5.1.0
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^22.3.0
  get_it: ^7.7.0
  http: ^1.2.2
  image_cropper: ^8.1.0
  image_picker: ^1.1.2
  injectable: ^2.5.0
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  photo_manager: ^3.2.0
  photo_manager_image_provider: ^2.0.0
  photo_view: ^0.15.0
  shimmer: ^3.0.0
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3
  uuid: ^4.4.2
  xml: ^6.5.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.10.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/env
